"""Initial  PG migration

Revision ID: 2312173edd8b
Revises: 
Create Date: 2025-09-30 04:35:50.645219

"""
from datetime import datetime
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2312173edd8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('executing_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_uuid'), 'wallets', ['uuid'], unique=True)
    # ### end Alembic commands ###

    op.execute(
           sa.text("""
               INSERT INTO wallets (title, description, uuid, balance, executing_date)
               VALUES (:title, :description, :uuid, :balance, :executing_date)
           """).bindparams(
               title="Основной кошелек",
               description="Автоматически созданный кошелек",
               uuid=uuid.UUID("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
               balance=1000.00,
               executing_date=datetime.now()
           )
       )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_uuid'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
