"""New structure model

Revision ID: 687021b7900c
Revises: 4206be972834
Create Date: 2025-09-29 04:40:25.730902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687021b7900c'
down_revision: Union[str, Sequence[str], None] = '4206be972834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('wallets_uuid_key'), 'wallets', type_='unique')
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_index(op.f('ix_wallets_uuid'), 'wallets', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_uuid'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.create_unique_constraint(op.f('wallets_uuid_key'), 'wallets', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
